FROM openjdk
MAINTAINER Dipankar Chatterjee <dipankar.c@hcl.com>
ADD target/account-service-1.0.jar account-service-1.0.jar
ENTRYPOINT exec java -jar /account-service-1.0.jar account-service
EXPOSE 2222